---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}

library(p8105.datasets)
library(tidyverse)
library(plotly)
library(flexdashboard)
library(lubridate)
data("rest_inspec")
```

```{r plot1, include = FALSE, message = FALSE, warning = FALSE}

plot1 = sample_n(rest_inspec, 1000) %>%
filter(grade %in% c("A", "B", "C")) %>%
mutate_at(vars(grade_date), funs(year, month, day)) %>%
group_by(year, grade) %>%
count()  
 
```

```{r plot2, include = FALSE, message = FALSE, warning = FALSE}
plot2 = rest_inspec%>%
  drop_na(grade) %>%
  filter(cuisine_description %in% c("French", "English","Polish","Portuguese", "Greek", "Italian" )) %>%
  sample_n(1000)
```


```{r plot3, include = FALSE, message = FALSE, warning = FALSE}
plot3 = rest_inspec%>%  drop_na(score) %>%
  sample_n(1000)
 
```

Column {data-width=600}
-----------------------------------------------------------------------
```{r box}

plot2 %>%
  plot_ly(y = ~score, color = ~cuisine_description, type = "box", colors = "viridis", showlegend = FALSE) %>%
  layout(title = 'Distribution of scores for European cuisines',
         xaxis = list(title = 'Cuisine',
                      zeroline = TRUE),
         yaxis = list(title = 'Score'))
```


Column {data-width=400}
-----------------------------------------------------------------------

```{r trends}

plot1 %>%
  plot_ly(
    x = ~year, y = ~n, type = "bar", color = ~grade) %>%
  layout(title = 'Distribution of detected violations across years group by year',
         xaxis = list(title = 'Year',
                      zeroline = TRUE),
         yaxis = list(title = 'Number of violations'))
```

```{r scatter}

plot3%>%
  plot_ly(y = ~score, x = ~boro, type = "scatter", mode = "markers") %>%
  layout(title = 'Violation scores for different boroughs',
         xaxis = list(title = 'Borough',
                      zeroline = TRUE),
         yaxis = list(title = 'Score'))
```